insert into signal_catalog (code, group_name, description, user_label, default_weight, severity, is_active)
values
  ('emotional_pressure', 'interaction', 'Apela a emociones para apurar la decisión.', 'Presión emocional', 10, 'medium', true),
  ('urgency_language', 'urgency', 'Usa lenguaje de urgencia o inmediatez.', 'Lenguaje urgente', 8, 'medium', true),
  ('secrecy_request', 'interaction', 'Pide mantener el asunto en secreto.', 'Pedido de secreto', 12, 'high', true),
  ('identity_change', 'interaction', 'Dice que cambió de número o identidad de contacto.', 'Cambio repentino de identidad', 15, 'high', true),
  ('new_number_claim', 'interaction', 'Afirma que está escribiendo desde un número nuevo.', 'Número nuevo inesperado', 14, 'high', true),
  ('urgent_transfer', 'urgency', 'Pide una transferencia urgente.', 'Transferencia urgente', 16, 'high', true),
  ('deadline_pressure', 'urgency', 'Impone un plazo corto para actuar.', 'Presión por plazo', 9, 'medium', true),
  ('transfer_request', 'payment', 'Solicita transferencia de dinero.', 'Pedido de transferencia', 14, 'high', true),
  ('deposit_request', 'payment', 'Solicita seña o depósito.', 'Pedido de seña', 10, 'medium', true),
  ('off_platform_payment', 'payment', 'Pide pagar por fuera de la plataforma original.', 'Pago fuera de plataforma', 16, 'high', true),
  ('asks_for_credentials', 'payment', 'Pide claves o credenciales sensibles.', 'Pedido de credenciales', 20, 'critical', true),
  ('asks_for_otp', 'payment', 'Pide un código de verificación u OTP.', 'Pedido de código de verificación', 22, 'critical', true),
  ('cbu_shared', 'payment', 'Comparte un CBU explícito.', 'CBU compartido', 7, 'medium', true),
  ('alias_shared', 'payment', 'Comparte un alias para cobrar.', 'Alias compartido', 5, 'low', true),
  ('authority_impersonation', 'identity', 'Se presenta como autoridad, policía o justicia.', 'Supuesta autoridad', 20, 'critical', true),
  ('bank_impersonation', 'identity', 'Se presenta como banco o entidad financiera.', 'Supuesto banco', 20, 'critical', true),
  ('support_impersonation', 'identity', 'Se presenta como soporte o asistencia.', 'Supuesto soporte', 15, 'high', true),
  ('family_impersonation', 'identity', 'Se presenta como familiar o conocido cercano.', 'Supuesto familiar', 15, 'high', true),
  ('inconsistent_identity', 'identity', 'Los datos de identidad no son consistentes entre sí.', 'Identidad inconsistente', 10, 'medium', true),
  ('threatens_arrest', 'authority', 'Amenaza con arresto, allanamiento o consecuencias penales.', 'Amenaza con arresto o allanamiento', 22, 'critical', true),
  ('threatens_legal_action', 'authority', 'Amenaza con acciones legales o judiciales.', 'Amenaza legal', 15, 'high', true),
  ('bribery_request', 'authority', 'Pide dinero para evitar consecuencias o resolver el caso.', 'Pedido de coima o pago para resolver', 20, 'critical', true),
  ('platform_bypass', 'platform', 'Desvía la operación fuera de la plataforma original.', 'Desvío fuera de plataforma', 16, 'high', true),
  ('suspicious_link', 'platform', 'Incluye links dudosos o inconsistentes.', 'Link sospechoso', 14, 'high', true),
  ('channel_shift', 'platform', 'Insiste en mover la conversación a otro canal.', 'Cambio de canal', 10, 'medium', true),
  ('external_presence_inconsistent', 'external', 'La presencia pública encontrada no coincide con lo declarado.', 'Presencia externa inconsistente', 10, 'medium', true),
  ('domain_recently_created', 'external', 'El dominio parece nuevo o poco confiable.', 'Dominio con señales débiles', 14, 'high', true),
  ('website_unreachable', 'external', 'El sitio no responde o falla al abrir.', 'Sitio no disponible', 5, 'low', true),
  ('unsolicited_contact', 'trust_reducer', 'El contacto llega sin contexto previo.', 'Contacto no solicitado', 8, 'medium', true),
  ('price_too_good', 'trust_reducer', 'La oferta parece demasiado conveniente.', 'Oferta demasiado conveniente', 9, 'medium', true),
  ('verified_identity_signal', 'trust_builder', 'Hay una señal parcial de identidad verificada.', 'Señal parcial de identidad verificada', -8, 'info', true),
  ('payment_on_delivery_available', 'trust_builder', 'Existe una modalidad de pago menos riesgosa y controlada.', 'Pago contra entrega disponible', -6, 'info', true),
  ('official_platform_interaction', 'trust_builder', 'La interacción sigue un canal oficial de la plataforma.', 'Interacción en canal oficial', -8, 'info', true)
on conflict (code) do update
set
  group_name = excluded.group_name,
  description = excluded.description,
  user_label = excluded.user_label,
  default_weight = excluded.default_weight,
  severity = excluded.severity,
  is_active = excluded.is_active;
